[config]
schemaVersion = "0.0.1"

[package]
namespace = "MT2"
name = "Steward_Clan"
versionNumber = "0.6.0"
description = "Monster Train 2 Clan"
websiteUrl = "https://github.com/Monster-Train-2-Modding-Group/StewardClan"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
MT2-Trainworks_Reloaded = "0.7.2"
Conductor-Conductor = "0.4.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./"

[[build.copy]]
source = "./plugin_build"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = [ "monster-train-2" ]
